#!/bin/bash
set -e

VERSION="$1"
VERSION_TAG="$2"
GITHUB_SHA="$3"
GITHUB_REF_NAME="$4"
GITHUB_REPOSITORY="$5"

echo "📝 Generating release notes..."

# Get recent commits for changelog
CHANGELOG=$(git log --oneline -10 --pretty=format:"- %s" | head -5)

# Start building release notes
cat > release-notes.md << EOF
# KM271-WiFi Hardware Release ${VERSION}

**Release Date**: $(date -u '+%Y-%m-%d %H:%M:%S UTC')  
**Git Commit**: $(echo "${GITHUB_SHA}" | cut -c1-8)  
**Branch**: ${GITHUB_REF_NAME}
**Version**: ${VERSION}

## 🔧 Hardware Components

This release includes production-ready files for:

EOF

# Add hardware components dynamically
for zip_file in final-release/*-HardwareRelease-${VERSION}.zip; do
  if [ -f "$zip_file" ]; then
    # Extract project name from ZIP filename
    project_name=$(basename "$zip_file" | sed "s/-HardwareRelease-${VERSION}\.zip$//")
    
    # Determine description based on project name
    case "$project_name" in
      "KM217-WiFi")
        description="KM217-WiFi Main Board"
        ;;
      "KM271-WiFi")
        description="KM271-WiFi Main Board"
        ;;
      "ETH_W5500")
        description="ETH_W5500 Extension Board"
        ;;
      *)
        description="$project_name Board"
        ;;
    esac
    
    cat >> release-notes.md << EOF
### 📋 $description
- Complete Gerber files for PCB manufacturing
- Drill files in Gerber format
- Schematic and PCB layout documentation (PDF)
- 3D STEP model for mechanical integration
- Assembly diagrams and component placement guides

EOF
  fi
done

# Continue with rest of release notes
cat >> release-notes.md << EOF
## 📚 Documentation

- Complete user documentation (English/German)
- Hardware description and technical specifications
- Getting started guides
- Component datasheets and references

## 📦 Release Assets

| Asset | Description | Format |
|-------|-------------|---------|
EOF

# Add asset table dynamically
for zip_file in final-release/*.zip; do
  if [ -f "$zip_file" ]; then
    filename=$(basename "$zip_file")
    
    # Determine description based on filename
    if [[ "$filename" == *"Documentation"* ]]; then
      description="Complete documentation package"
    elif [[ "$filename" == *"HardwareRelease"* ]]; then
      project_name=$(echo "$filename" | sed "s/-HardwareRelease-${VERSION}\.zip$//")
      description="$project_name manufacturing files"
    else
      description="Release package"
    fi
    
    echo "        | \`$filename\` | $description | ZIP |" >> release-notes.md
  fi
done

# Finish release notes
cat >> release-notes.md << EOF

## 🔐 File Integrity

All release assets include SHA256 checksums for integrity verification. See \`checksums.txt\` for details.

## 🏭 Manufacturing Ready

All hardware files in this release are:
- ✅ Validated and tested
- ✅ Generated with production-grade settings
- ✅ Ready for PCB manufacturing
- ✅ Include complete documentation

## 📋 Recent Changes

${CHANGELOG}

## 🆘 Support

For questions or issues with this release, please:
- Check the included documentation
- Review the hardware description files
- Open an issue on GitHub if problems persist

---

**Automated Release** - Generated by GitHub Actions
EOF

echo "Release Notes:"
cat release-notes.md

echo ""
echo "📊 Release Summary"
echo "=================="
echo "Release Tag: ${VERSION_TAG}"
echo "Version: ${VERSION}"
echo "Commit: $(echo "${GITHUB_SHA}" | cut -c1-8)"
echo "Assets:"
ls -la final-release/
echo ""
echo "✅ Release created successfully!"
echo "🔗 Release URL: https://github.com/${GITHUB_REPOSITORY}/releases/tag/${VERSION_TAG}"
