substitutions:
  slug:                  esp32-km271
  name:                  KM271
  switch_name:           KM271

packages:
  device:                !include devices/esp32dev_v4_espidf.yaml
  base:                  !include common/default_base.yaml

uart:
  id:                    uart_bus
  tx_pin:                GPIO2
  rx_pin:                GPIO4
  baud_rate:             2400

external_components:
  - source:              github://the78mole/esphome_components@main
 #oder lokal in esphome/components/km271_wifi
 #  - source:            components
    components:          [ km271_wifi ]

km271_wifi:
  - id:                  budoil
    uart_id:             uart_bus

# "Status LED1"
status_led:
  pin:
    number:              GPIO21
    inverted:            true

sensor:
  - platform:            adc
    pin:                 36
    unit_of_measurement: "V"
    name:                "R2107 5V Supply"
    accuracy_decimals:   2
    update_interval:     60s
    attenuation:         6dB
    filters:
      - multiply:        2.274
      - sliding_window_moving_average:
          window_size:   16
          send_every:    4

logger:
  logs:
    mqtt.component:      ERROR
    mqtt.client:         ERROR

mqtt:
  broker:                !secret mqtt_server_local
  port:                  1883
  username:              !secret mqtt_username_local
  password:              !secret mqtt_password_local
  discovery:             false
